<div class=one>

Name: Fatima Momin  <br>
Email: fatimamomina423@gmail.com  <br>
GitHub: https://github.com/dashboard  <br>
Title:  Assignment no 2 (Scenario Based Operations on Numpy) <br>

</div>

<style>
.one {
    color: orangered;
    text-align:center;
}
</style>

In [35]:
%pip install pandas 
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import pandas as pd
import numpy as np

<h1>Sales Data Analysis</h1>
<style>
h1{
 color: orange;   
}    
</style>

In [2]:
Daily_sales =np.array([105, 150, 200, 125, 200, 250, 180, 110, 160, 230, 210, 190, 140, 180, 200, 120, 170, 334, 190, 100, 150, 210, 180, 130, 50, 200, 110, 160, 230])
Daily_sales

array([105, 150, 200, 125, 200, 250, 180, 110, 160, 230, 210, 190, 140,
       180, 200, 120, 170, 334, 190, 100, 150, 210, 180, 130,  50, 200,
       110, 160, 230])

In [3]:
Total_sales=Daily_sales.sum()
Total_sales

np.int64(4964)

In [4]:
Average_sales=Daily_sales.mean()
Average_sales

np.float64(171.17241379310346)

In [5]:
Highest_Day_sales=Daily_sales.argmax()+1
Highest_Day_sales

np.int64(18)

In [6]:
HeighestSale_Amount= Daily_sales.max()
HeighestSale_Amount

np.int64(334)

<h1>Weather Data Processing</h1>
<style>
h1{
 color: orange;   
}    
</style>

In [7]:
Weekly_Temperatures = np.array([[31,43,33,37,32,36,30],
                                [39,42,34,31,36,32,38],
                                [33,41,30,32,35,38,36],
                               ])
Weekly_Temperatures 

array([[31, 43, 33, 37, 32, 36, 30],
       [39, 42, 34, 31, 36, 32, 38],
       [33, 41, 30, 32, 35, 38, 36]])

In [8]:
Veg_temp_Day=Weekly_Temperatures.mean(axis=0)
Veg_temp_Day

array([34.33333333, 42.        , 32.33333333, 33.33333333, 34.33333333,
       35.33333333, 34.66666667])

In [9]:
for day in range(7):
    print(f"Day {day+1}: {Veg_temp_Day[day]:.2f} degrees Celsius")

Day 1: 34.33 degrees Celsius
Day 2: 42.00 degrees Celsius
Day 3: 32.33 degrees Celsius
Day 4: 33.33 degrees Celsius
Day 5: 34.33 degrees Celsius
Day 6: 35.33 degrees Celsius
Day 7: 34.67 degrees Celsius


<h1>Financial Analysis</h1>
<style>
h1{
 color: orange;   
}    
</style>

In [10]:
Prices = np.array([109, 115, 104, 135, 136, 137, 138, 140, 142, 144, 145, 147, 148,149, 150, 151])
Prices

array([109, 115, 104, 135, 136, 137, 138, 140, 142, 144, 145, 147, 148,
       149, 150, 151])

In [12]:
Monthly_return = (Prices[-1]-Prices[0])/Prices[0]*100
Monthly_return 

np.float64(38.53211009174312)

<h1>Student Grades Analysis</h1>
<style>
h1{
 color: orange;   
}    
</style>

In [13]:
Grades_std = np.array([[70, 95, 88],[75, 60, 80],[80, 89, 92],[81, 77, 65]])
Grades_std

array([[70, 95, 88],
       [75, 60, 80],
       [80, 89, 92],
       [81, 77, 65]])

In [14]:
Avg_grade_pr_std = np.mean(Grades_std, axis=1)
Avg_grade_pr_std

array([84.33333333, 71.66666667, 87.        , 74.33333333])

In [15]:
Class_avg_per_subj = np.mean(Grades_std, axis=0)
Class_avg_per_subj

array([76.5 , 80.25, 81.25])

<h1>Image Processing</h1>
<style>
h1{
 color: orange;   
}    
</style>

In [16]:
img = np.array([[0, 130, 255],[50, 167, 138],[255, 190, 0]])
img

array([[  0, 130, 255],
       [ 50, 167, 138],
       [255, 190,   0]])

In [17]:
#Img range 0 to 1
normalized_img = img / 255.0
normalized_img

array([[0.        , 0.50980392, 1.        ],
       [0.19607843, 0.65490196, 0.54117647],
       [1.        , 0.74509804, 0.        ]])

<h1>Population Growth Analysis</h1>
<style>
h1{
 color: orange;   
}    
</style>

In [18]:
Population_Data = np.array([1700, 1650, 1800, 2300, 1200, 1050, 1300, 1100, 1600, 1500])

Population_Data

array([1700, 1650, 1800, 2300, 1200, 1050, 1300, 1100, 1600, 1500])

In [19]:
annual_growth_rate = np.diff(Population_Data) / Population_Data[:-1] * 100
highest_growth_year = np.argmax(annual_growth_rate) + 1  

In [20]:
annual_growth_rate


array([ -2.94117647,   9.09090909,  27.77777778, -47.82608696,
       -12.5       ,  23.80952381, -15.38461538,  45.45454545,
        -6.25      ])

In [21]:
highest_growth_year

np.int64(8)

<h1>Traffic Data Analysis</h1>
<style>
h1{
 color: orange;   
}    
</style>

In [22]:
#Data: 7 days, 24 hrs
Trafic = np.random.randint(20, 170, size=(7, 24))
Trafic 

array([[141, 110, 155, 168, 155,  93,  46, 169,  57,  64,  55, 108, 131,
         46,  22, 136,  26, 135, 129,  81, 156,  67,  41, 152],
       [163,  53,  56,  32,  46,  47, 108,  67, 168,  56,  84,  43, 164,
        150,  64,  36,  86, 153,  46,  45, 137, 137, 155, 169],
       [125,  72,  83,  52, 162, 130, 141, 143, 112, 136, 113,  24,  81,
         29, 159,  38,  78, 133,  54,  38,  58, 120, 111,  85],
       [154, 113, 159,  95,  82, 144, 162,  81, 127,  94, 137,  93,  73,
        116,  88,  39,  88, 122,  33,  95,  25,  75,  44, 132],
       [169, 143, 144, 114, 118,  20,  78, 141, 149,  53, 162,  63, 160,
         65, 162,  46,  58,  69, 120,  69,  49,  66, 117, 150],
       [160,  24,  43,  68, 135, 155,  88, 138, 167,  74, 104, 165, 146,
         34,  79,  28,  90,  76,  40, 113,  44, 143,  56,  42],
       [127,  84, 109, 117,  83,  30,  30, 107,  52,  44,  52, 113, 164,
         89,  80,  66,  97, 161,  76,  86, 164, 154, 139,  68]],
      dtype=int32)

In [23]:
total_trafic_per_day = np.sum(Trafic, axis=1)
Busy_hour_in_wk = np.argmax(np.sum(Trafic, axis=0))

In [24]:
total_trafic_per_day 

array([2443, 2265, 2277, 2371, 2485, 2212, 2292])

In [25]:
Busy_hour_in_wk

np.int64(0)

<h1>Product Inventory Management</h1>
<style>
h1{
 color: orange;   
}    
</style>

In [26]:
Stock_levels = np.array([55, 65, 75, 35, 50, 25])


In [27]:
#threshold 50 units
reorder_list = np.where(Stock_levels < 50)[0]

reorder_list

array([3, 5])

<h1>Game Score Analysis</h1>
<style>
h1{
 color: orange;   
}    
</style>

In [28]:
#Data of 5 players and 10 rounds
Score = np.random.randint(80, 320, size=(5, 20))

In [29]:
# Player with highest ave score
highest_avg_scoreplayer = np.argmax(np.mean(Score, axis=1))

# Round with highest T score
highest_total_scorer_ound = np.argmax(np.sum(Score, axis=0))

In [30]:
highest_avg_scoreplayer

np.int64(0)

In [31]:
highest_total_scorer_ound

np.int64(11)

<h1>Financial Portfolio Analysis</h1>
<style>
h1{
 color: orange;   
}    
</style>

In [32]:
# 4 assets, 30 days)
Return = np.random.randn(6, 40)

Overall_daily_return = np.mean(Return, axis=0)

# Asset with highest volatility
Highest_volatility_asset = np.argmax(np.std(Return, axis=1))

Overall_daily_return

array([-0.21711966,  0.23003659,  0.19974608,  0.35961285, -0.21556855,
        1.1851394 ,  0.35817522,  0.36419697,  0.44440265, -0.60717772,
       -0.08487064, -0.20413967, -0.21959965,  0.63725634, -0.27998147,
       -0.50967159, -0.08602035, -0.04921926,  0.25592465, -0.28236819,
       -0.22123653, -0.67852711,  0.01129805, -0.08021957,  0.05991604,
       -0.11341493,  0.50238652, -0.18757781, -0.02100366,  0.06511792,
       -0.017768  , -0.08591016, -0.28220924, -0.47808633,  0.01266703,
        0.0821962 , -0.78728157,  0.26709385, -0.00207845,  0.57531266])

In [33]:
Highest_volatility_asset

np.int64(5)