<div class=one>

Name: Fatima Momin  <br>
Email: fatimamomina423@gmail.com  <br>
GitHub: https://github.com/dashboard  <br>
Title:  Assignment no 1 (Basic array operations) <br>

</div>

<style>
.one {
    color: yellow;
    text-align:center;
}
</style>

In [14]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd
import numpy as np

<h1>Basic Array Operations</h1>
<style>
h1{
 color: green;   
}    
</style>

#### Arrays of 1D, 2D & 3D

In [3]:
# 1D Array
array1 = np.array([1, 2, 3, 4, 5])  

# 2D Array  
array2 = np.array([[1, 2, 3], [4, 5, 6]])  

# 3D Array  
array3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])   

print("1D Array:\n", array1)  
print("2D Array:\n", array2)  
print("3D Array:\n", array3)


1D Array:
 [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Slicing on each array

In [4]:
# Slicing 1D array (first 2 elements)
print("Sliced 1D:", array1[:2])  

# Slicing 2D array (second row)
print("Sliced 2D (first row):\n", array2[1, :])  

# Slicing 3D array (extracting first matrix)
print("Sliced 3D (first matrix):\n", array3[0, :, :])  


Sliced 1D: [1 2]
Sliced 2D (first row):
 [4 5 6]
Sliced 3D (first matrix):
 [[1 2]
 [3 4]]


#### Airthematic Operations

In [22]:
# On 1D array
# Adding 2 to each element
print("Addition:\n", array1 + 2)  

# Subtracting 1 from each element
print("Subtraction:\n", array1 - 1)  

# Multiplication by 3
print("Multiplication:\n", array1 * 3)  

# Division by 2
print("Division:\n", array1 / 2)  


Addition:
 [3 4 5 6 7]
Subtraction:
 [0 1 2 3 4]
Multiplication:
 [ 3  6  9 12 15]
Division:
 [0.5 1.  1.5 2.  2.5]


In [23]:
#on 2D array
print("Addition:\n", array2 + 1) 
print("Subtraction:\n", array2 - 2) 
print("Multiplication:\n", array2 * 5) 
print("Division:\n", array2 /4)  

Addition:
 [[2 3 4]
 [5 6 7]]
Subtraction:
 [[-1  0  1]
 [ 2  3  4]]
Multiplication:
 [[ 5 10 15]
 [20 25 30]]
Division:
 [[0.25 0.5  0.75]
 [1.   1.25 1.5 ]]


In [24]:
#on 3D array
print("Addition:\n", array3 + 3)  
print("Subtraction:\n", array3 - 2)  
print("Multiplication:\n", array3 * 10)  
print("Division:\n", array3 / 2)  

Addition:
 [[[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
Subtraction:
 [[[-1  0]
  [ 1  2]]

 [[ 3  4]
  [ 5  6]]]
Multiplication:
 [[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
Division:
 [[[0.5 1. ]
  [1.5 2. ]]

 [[2.5 3. ]
  [3.5 4. ]]]


<h1>Array Creation and Manipulation</h1>
<style>
h1{
 color: green;   
}    
</style>

In [ ]:
# Using arange
arr_arange = np.arange(1, 10, 2) # start stop stepwise

# Using linspace 
arr_linspace = np.linspace(1, 10, 5)  # start stop interval

# Using zeros 
arr_zeros = np.zeros((2, 3))  # 2 rows, 3 columns filled with 0

# Using ones 
arr_ones = np.ones((3, 2))  # 3 rows, 2 columns filled with 1

# Using eye 
arr_eye = np.eye(3)  # 3x3 identity matrix

# Using random
arr_random = np.random.rand(2, 3)  # 2x3 array with random values

print("Arange:\n", arr_arange)
print("Linspace:\n", arr_linspace)
print("Zeros:\n", arr_zeros)
print("Ones:\n", arr_ones)
print("Identity Matrix:\n", arr_eye)
print("Random:\n", arr_random)

Arange:
 [1 3 5 7 9]
Linspace:
 [ 1.    3.25  5.5   7.75 10.  ]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random:
 [[0.43979074 0.75845237 0.14099463]
 [0.20692239 0.10447654 0.66031697]]


#### Reshaping Array

In [9]:
arr = np.arange(1, 10)  # 1D array with values from 1 to 9
arr_reshaped = arr.reshape(3, 3)  # Reshaping to 3x3 matrix

print("Original Array:\n", arr)
print("Reshaped (3x3):\n", arr_reshaped)


Original Array:
 [1 2 3 4 5 6 7 8 9]
Reshaped (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# concatenate arrays
arr = np.concatenate((arr1, arr2))
print(arr)

# with 2D array
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenation (Vertical and Horizontal)
arr_concat_v = np.vstack((arr1, arr2))  # Vertical stacking
arr_concat_h = np.hstack((arr1, arr2))  # Horizontal stacking

# Splitting an Array
arr_split = np.split(arr_concat_v, 2)  # Splitting into 2 equal parts

print("Vertical Concatenation:\n", arr_concat_v)
print("Horizontal Concatenation:\n", arr_concat_h)
print("Split Arrays:\n", arr_split)


[1 2 3 4 5 6]
Vertical Concatenation:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Concatenation:
 [[1 2 5 6]
 [3 4 7 8]]
Split Arrays:
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


<h1>Statical Operations</h1>
<style>
h1{
 color: green;   
}    
</style>

In [26]:
arr_stat = np.array([[1, 2, 3], [4, 5, 6]])

# Mean, Median, Standard Deviation
mean_val = np.mean(arr_stat)
median_val = np.median(arr_stat)
std_dev = np.std(arr_stat)

# Min and Max
min_val = np.min(arr_stat)
max_val = np.max(arr_stat)

# Sum and Product
sum_val = np.sum(arr_stat)
prod_val = np.prod(arr_stat)

print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_dev)
print("Min:", min_val, "Max:", max_val)
print("Sum:", sum_val, "Product:", prod_val)


Mean: 3.5
Median: 3.5
Standard Deviation: 1.707825127659933
Min: 1 Max: 6
Sum: 21 Product: 720


<h1>BroadCasting</h1>
<style>
h1{
 color: green;   
}    
</style>

In [27]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2

# Broadcasting: Multiplying every element of arr1 by scalar
result = arr1 * scalar

print("Original Array:\n", arr1)
print("After Broadcasting (Multiplication by 2):\n", result)

Original Array:
 [[1 2 3]
 [4 5 6]]
After Broadcasting (Multiplication by 2):
 [[ 2  4  6]
 [ 8 10 12]]


#### Broadcasting with different shapes of arrays

In [13]:
arr1 = np.array([1, 2, 3])  # 1D array
arr2 = np.array([[1], [2]])  # 2D column vector

# Broadcasting: Adding a 1D array to a 2D array
broadcasted_sum = arr1 + arr2  

print("After Broadcasting Addition:\n", broadcasted_sum)


After Broadcasting Addition:
 [[2 3 4]
 [3 4 5]]


In [15]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])  
arr1D = np.array([1, 2, 3])  

# Broadcasting: 2D array is added to each row of the 1D array
result = arr2D + arr1D  

print("Original 2D Array:\n", arr2D)  
print("1D Array:\n", arr1D)  
print("Broadcasted Addition:\n", result)


Original 2D Array:
 [[1 2 3]
 [4 5 6]]
1D Array:
 [1 2 3]
Broadcasted Addition:
 [[2 4 6]
 [5 7 9]]


<h1>Linear Algebra</h1>
<style>
h1{
 color: green;   
}    
</style>

In [16]:
A = np.array([[1, 2], [3, 4]])  
B = np.array([[5, 6], [7, 8]])  

# Matrix multiplication
result = np.dot(A, B)  # or A @ B  

print("Matrix Multiplication:\n", result)

Matrix Multiplication:
 [[19 22]
 [43 50]]


In [17]:
A = np.array([[1, 2], [3, 4]])  

# Determinant
det_A = np.linalg.det(A)  

print("Determinant of A:", det_A)

Determinant of A: -2.0000000000000004


In [18]:
A = np.array([[1, 2], [3, 4]])  

# Inverse of A
A_inv = np.linalg.inv(A)  

print("Inverse of A:\n", A_inv)

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [19]:
A = np.array([[1, 2], [3, 4]])  

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)  

print("Eigenvalues:\n", eigenvalues)  
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


#### Solving a Sytem of Linear Equations

In [21]:
A = np.array([[2, 3], [1, 2]])  
B = np.array([8, 5])  
# Ax=B    x= A inverse B 
# Solving for x
x = np.linalg.solve(A, B)  

print("Solution for x:\n", x)

Solution for x:
 [1. 2.]


<h1>Advanced Indexing & Slicing</h1>
<style>
h1{
 color: green;   
}    
</style>

In [29]:
# Boolean Indexing

arr = np.array([10, 20, 30, 40, 50])

# Get elements greater than 25
filtered_arr = arr[arr > 25]

print("Filtered Elements:", filtered_arr)

Filtered Elements: [30 40 50]


In [31]:
# Selecting Even Numbers

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Get even numbers
even_numbers = arr[arr % 2 == 0]

print("Even Numbers:", even_numbers)

Even Numbers: [2 4 6 8]


In [32]:
# Replacing Values Based on Condition
arr = np.array([5, 15, 25, 35, 45])

# Replace values greater than 20 with 100
arr[arr > 20] = 100

print("Modified Array:", arr)

Modified Array: [  5  15 100 100 100]


#### Fancy Indexing

In [33]:
# Selecting Specific Elements

arr = np.array([10, 20, 30, 40, 50])

# Select elements at positions 0, 2, and 4
selected = arr[[0, 2, 4]]

print("Selected Elements:", selected)


Selected Elements: [10 30 50]


In [34]:
# Fancy Indexing in a 2D Array
arr_2D = np.array([[10, 20, 30], 
                   [40, 50, 60], 
                   [70, 80, 90]])

# Select elements from row 0 and row 2
selected_rows = arr_2D[[0, 2]]

print("Selected Rows:\n", selected_rows)


Selected Rows:
 [[10 20 30]
 [70 80 90]]


#### Advanced Slicing

In [35]:
# Slicing a 1D Array

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# Extract elements from index 2 to 5
slice_1 = arr[2:6]

print("Sliced Array:", slice_1)


Sliced Array: [30 40 50 60]


In [36]:
# Slicing a 2D Array
arr_2D = np.array([[1, 2, 3, 4], 
                    [5, 6, 7, 8], 
                    [9, 10, 11, 12]])

# Extract rows 0-1 and columns 1-2
sliced_2D = arr_2D[:2, 1:3]

print("Sliced 2D Array:\n", sliced_2D)


Sliced 2D Array:
 [[2 3]
 [6 7]]


In [37]:
# Reversing an Array Using Slicing

arr = np.array([10, 20, 30, 40, 50])

# Reverse the array
reversed_arr = arr[::-1]

print("Reversed Array:", reversed_arr)


Reversed Array: [50 40 30 20 10]


In [38]:
# Stride Slicing

arr = np.array([10, 20, 30, 40, 50, 60, 70])

# Extract every second element
stride_slice = arr[::2]

print("Elements with Stride 2:", stride_slice)


Elements with Stride 2: [10 30 50 70]


<h1>Random Sampling</h1>
<style>
h1{
 color: green;   
}    
</style>

In [40]:
# Generate Random Integers

# Generate 5 random integers between 1 and 50
random_integers = np.random.randint(1, 50, size=5)

print("Random Integers:", random_integers)

Random Integers: [16 42  3  5 18]


In [42]:
# Generate Random Floating-Point Numbers

# Generate 5 random floats between 0 and 1
random_floats = np.random.rand(5)

print("Random Floats:", random_floats)


Random Floats: [0.83043288 0.93915219 0.31095521 0.60753012 0.77158216]


In [43]:
# Generate Random Numbers from a Normal Distribution

# Generate 5 random numbers from a normal distribution
random_normal = np.random.randn(5)

print("Random Normal Distribution:", random_normal)


Random Normal Distribution: [-0.55365161  0.39829325  2.80358392 -0.01215786  0.58131595]


In [44]:
# Normal distribution with mean = 50, standard deviation = 10
custom_normal = np.random.normal(50, 10, 5)

print("Custom Normal Distribution:", custom_normal)


Custom Normal Distribution: [40.45982325 49.11741575 60.65488867 54.14763659 54.61991871]


#### Create Random Samples from a Dataset

In [45]:
# Select Random Elements from a List

arr = np.array([10, 20, 30, 40, 50, 60])

# Select 3 random elements
random_samples = np.random.choice(arr, 3)

print("Random Samples:", random_samples)


Random Samples: [10 10 10]


In [46]:
# Select Random Elements Without Replacement

# Select 3 unique elements (no repetition)
unique_samples = np.random.choice(arr, 3, replace=False)

print("Unique Random Samples:", unique_samples)


Unique Random Samples: [40 30 60]


#### Random Shuffling of an Array

In [47]:
# Shuffle an Array In-Place

arr = np.array([1, 2, 3, 4, 5])

np.random.shuffle(arr)  # Shuffles array in-place

print("Shuffled Array:", arr)


Shuffled Array: [1 2 3 4 5]


In [48]:
# Return a New Shuffled Array

arr = np.array([10, 20, 30, 40, 50])

shuffled_arr = np.random.permutation(arr)

print("Original Array:", arr)
print("Shuffled Copy:", shuffled_arr)


Original Array: [10 20 30 40 50]
Shuffled Copy: [30 20 40 10 50]
