<div class=one>

Name: Fatima Momin  <br>
Email: fatimamomina423@gmail.com  <br>
GitHub: https://github.com/dashboard  <br>
Title:  Numpy Practice <br>

</div>

<style>
.one {
    color: red;
    text-align:center;
}
</style>

**Numpy Practise**

**Step 1: Install Libraries**

In [1]:
%pip install pandas
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import pandas as pd 
import numpy as np

In [4]:
array=np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [5]:
print(type(array))

<class 'numpy.ndarray'>


# 2D Array in Numpy

In [6]:
array=np.array([[1,2,3],[4,5,6]])
print(array)

[[1 2 3]
 [4 5 6]]


# 3D Array

In [7]:
array=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(array)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Array creation using build in method
np.zeros()

np.ones()

np.full()

np.arange()

np.linspace()

In [11]:
z_array=np.zeros((2,3))
ones_array=np.ones((3,4))
constant_array=np.full((2,2),4)
arange_array=np.arange(0,10,2)#start, stop, stepsize
linespace_array=np.linspace(0,1,5)#start, stop, interval

print("zero's array= \n",z_array)
print("one's array= \n",ones_array)
print("constant_array =\n",constant_array)
print("Arrange array =\n",arange_array)
print("linespace_array=\n",linespace_array)

zero's array= 
 [[0. 0. 0.]
 [0. 0. 0.]]
one's array= 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
constant_array =
 [[4 4]
 [4 4]]
Arrange array =
 [0 2 4 6 8]
linespace_array=
 [0.   0.25 0.5  0.75 1.  ]


# Creating array using random number generation

np.random.rand() from 0 to 1

np.random.randn()  from specific distrivution

np.random.randint() from given range

In [12]:
random_array=np.random.rand(2,3)
print(random_array)
normal_array=np.random.randn(2,3)
print("\n",random_array)
randint_array=np.random.randint(2,9)
print("\n",randint_array)

[[0.47096563 0.42170079 0.12482993]
 [0.10001533 0.00241602 0.41600325]]

 [[0.47096563 0.42170079 0.12482993]
 [0.10001533 0.00241602 0.41600325]]

 6


## Numpy array attribute and methods
**Reshaping**

In [13]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
newarr=arr.reshape(2,5) #important in image filterring
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Remove dimensions

In [14]:
newarr=newarr.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10]


## Dimension Checking

In [15]:
a=np.array(43)
b=np.array([1,3,45])
c=np.array([[2,4],[2,7]])

print(a.ndim)
print(b.ndim)
print(c.ndim)

0
1
2


## Using ndim Creating Dimensions

In [16]:
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


## Array Shape

In [17]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


## Data Type of Array

i-integer  
f-float  
c-complex float  
u-unsigned int  
m-timedelta  
S-string  

In [18]:
arr=np.array(["Apple","Banana","Cherry"])
print(arr.dtype)
arr=np.array([1,2,3,4,5], dtype='S')
print(arr.dtype)
arr=np.array([1,2,3,4,5], dtype='f')
print(arr.dtype)

<U6
|S1
float32


# Copying

In [19]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

arr=np.array([[1,2,3,4,5,6]])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[1, 2, 3, 4, 5, 6]]), array([], shape=(0, 6), dtype=int64), array([], shape=(0, 6), dtype=int64)]


# Joining

In [22]:

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Correct way to concatenate arrays
arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


# Deleting

In [24]:
arr1 = np.arange(10)  
print("Original Array:", arr1)

# Correct usage of np.delete()
arr1 = np.delete(arr1, 3)  
print("Array after deletion:", arr1)

Original Array: [0 1 2 3 4 5 6 7 8 9]
Array after deletion: [0 1 2 4 5 6 7 8 9]


# Sorting

In [25]:
arr1 = np.arange(10)[::-1]  # Reversed order for sorting demonstration
print("Original Array:", arr1)

# Sorting the array in ascending order
sorted_arr = np.sort(arr1)
print("Sorted Array:", sorted_arr)

Original Array: [9 8 7 6 5 4 3 2 1 0]
Sorted Array: [0 1 2 3 4 5 6 7 8 9]


# MAX & MIN

In [26]:
arr1 = np.array([4, 1, 8, 3, 6])

# Finding the maximum and minimum values
max_value = np.max(arr1)
min_value = np.min(arr1)

print("Original Array:", arr1)
print("Maximum Value:", max_value)
print("Minimum Value:", min_value)

Original Array: [4 1 8 3 6]
Maximum Value: 8
Minimum Value: 1
