<center>Name : Fatima Zahra<br>
Email : FatimaZahraAIML@hotmail.com<br>
Github : SyedaFatima55<br>
Title : Numpy Practices</center>

Install Libraries

In [1]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: C:\Users\HP\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: C:\Users\HP\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


Import Libraries

In [3]:
import pandas as pd

In [4]:
import numpy as np

Make an array

In [5]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


2D Array

In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


3D Array

In [7]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Array Creation using Built-in method

In [10]:
zarray=np.zeros((2,3))
onesarray=np.ones((3,4))
constant_array=np.full((2,2),4)

range_arr=np.arange(0,10,2)#start, stop, stepsize

linespace_arr=np.linspace(0,1,5)#start, stop, interval
print("zero's array= \n",zarray)
print("one's array= \n",onesarray)
print("constant_array =\n",constant_array)
print("Arrange array =\n",range_arr)
print("linespace_array=\n",linespace_arr)


zero's array= 
 [[0. 0. 0.]
 [0. 0. 0.]]
one's array= 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
constant_array =
 [[4 4]
 [4 4]]
Arrange array =
 [0 2 4 6 8]
linespace_array=
 [0.   0.25 0.5  0.75 1.  ]


Creating array using random number Generation

In [12]:
random_array=np.random.rand(2,3)
print(random_array)
normal_array=np.random.randn(2,3)
print("\n",random_array)
randint_array=np.random.randint(2,9)
print("\n",randint_array)

[[0.29955494 0.16389326 0.40984953]
 [0.9989474  0.91132187 0.49495436]]

 [[0.29955494 0.16389326 0.40984953]
 [0.9989474  0.91132187 0.49495436]]

 3


In [13]:
randint_array = np.random.randint(2, 9, (2, 3))
print("\n", randint_array)


 [[6 2 8]
 [2 3 5]]


Reshape Array

In [14]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
newarr=arr.reshape(2,5) #important in image filterring
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Remove Dimensions

In [15]:
newarr=newarr.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10]


Dimensions Checking

In [16]:
a=np.array(43)
b=np.array([1,3,45])
c=np.array([[2,4],[2,7]])

print(a.ndim)
print(b.ndim)
print(c.ndim)

0
1
2


Usind ndim creating dimensions

In [17]:
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


Array Shape

In [18]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


Data Type of Array

In [19]:
arr=np.array(["Apple","Banana","Cherry"])
print(arr.dtype)
arr=np.array([1,2,3,4,5], dtype='S')
print(arr.dtype)
arr=np.array([1,2,3,4,5], dtype='f')
print(arr.dtype)

<U6
|S1
float32


Copying

In [20]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

arr=np.array([[1,2,3,4,5,6]])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[1, 2, 3, 4, 5, 6]]), array([], shape=(0, 6), dtype=int64), array([], shape=(0, 6), dtype=int64)]
